### ISSUE TITLE
Please remove flags from TryHackMe writeups

### ISSUE THREAD

**Issue by Hydragyrum** [rudSarkar/rudSarkar.github.io#1]
It is against the site rules to display the flags in the writeups for tryhackme rooms. Please remove them from the writeups.

**Comment by rudSarkar** [comment]
Can you specify which one? There are few old boxes as well.

**Comment by Hydragyrum** [comment]
I saw Git and Crumpets to begin with. Also, please submit the writeup to the room :)

**Comment by Hydragyrum** [comment]
Also remove any passwords and other potentially sensitive information

**Comment by rudSarkar** [comment]
Okay! I will remove it in an hour and submit the write-up to the room. 

Thanks,
